version: '3.1'

services:

  production-nginx-container:
    container_name: 'production-nginx-container'
    image: lhoangphuong/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/lhoangphuong.ddns.net/fullchain.pem:/etc/letsencrypt/live/lhoangphuong.ddns.net/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/lhoangphuong.ddns.net/privkey.pem:/etc/letsencrypt/live/lhoangphuong.ddns.net/privkey.pem
    networks:
      - docker-network
  chat:
    container_name: 'chat'
    image: lhoangphuong/chat
    ports:
      - "5555:5555"
    networks:
      - docker-network

  whiteboard:
    container_name: 'whiteboard'
    image: lhoangphuong/whiteboard
    ports:
      - "7777:7777"
    networks:
      - docker-network

  mario:
    container_name: 'mario'
    image: pengbai/docker-supermario
    ports:
      - "8600:8080"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge


